# docker-compose.yml
# Docker Compose 파일 형식 버전 지정 (최신 버전 사용)
version: '3.8' 

# 이 파일에 정의된 서비스들
services:
  trot_player: 
    build: . 
    container_name: grandma_trot_player 
    privileged: true

    # 볼륨 마운트: 호스트 PC의 'audio' 폴더를 컨테이너 내부의 '/app/audio'로 연결합니다.
    # 이렇게 하면 컨테이너가 호스트 PC의 실제 음악 파일에 접근할 수 있습니다.
    volumes:
      - ./audio:/app/audio

    
    environment:
      - DISPLAY=host.docker.internal:0.0 # 6칸 들여쓰기
      # 만약 위의 설정으로 GUI가 나타나지 않으면, 아래 주석을 해제하고 'YOUR_PC_IP'를
      # 당신의 PC 실제 IP 주소(cmd에서 ipconfig로 확인)로 변경해 시도해 볼 수 있습니다.
      # # - DISPLAY=YOUR_PC_IP:0.0 # 주석 처리됨
      - QT_QPA_PLATFORM=offscreen 
      - ALSA_CARD=default 
      # - PULSE_SERVER=unix:/run/user/1000/pulse/native # PulseAudio 사용 시 (복잡)

    # 장치 마운트: 웹캠 접근 허용 설정
    # WSL2에서 'ls /dev/video*' 명령으로 확인된 웹캠 장치 경로를 명시적으로 마운트합니다.
    # (일반적으로 /dev/video0 이지만, 필요시 /dev/video1 등으로 변경 가능)
    devices: 
      - /dev/video0:/dev/video0 
      - /dev/snd:/dev/snd 

    # 네트워크 모드: 호스트 네트워크 사용
    # 컨테이너가 호스트 PC의 네트워크 스택을 직접 공유하도록 설정합니다.
    # 이는 컨테이너 내부의 GUI 앱이 호스트 PC의 X 서버(VcXsrv)와 통신하기 위해 필요합니다.
    # (보안상 완전히 격리되지 않지만, 로컬 GUI 앱 실행에는 가장 간단합니다.)
    network_mode: "host" 

    # 컨테이너 종료 시 자동 삭제 설정 (선택 사항)
    # 개발 중에는 주석 처리하여 컨테이너를 유지할 수 있으며,
    # 'docker-compose down' 시 컨테이너가 삭제됩니다.
    # restart: "no" # 컨테이너가 비정상 종료되더라도 자동으로 재시작하지 않음
    # remove: true # 컨테이너 중지 시 자동으로 컨테이너 삭제